/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package imageConfigration;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {


        BufferedImage image = ImageIO.read(new File("/home/ashqur/401/bitmap-transformer/app/src/main/resources/test2.bmp"));
        BitMap imageManpulation = new BitMap() ;
//        imageManpulation.invert(image);
//        imageManpulation.borader(image);
        System.out.println(imageManpulation.fon(5));
    }



}
