/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package imageConfigration;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {


        BufferedImage image = ImageIO.read(new File(args[0]));
        BitMap imageManpulation = new BitMap() ;
        switch(args[2]){
            case "invert":
                imageManpulation.invert(image,args[1]);
                break;
            case "boarder":
                imageManpulation.border(image,args[1]);
                break;
            case "randomize":
                imageManpulation.randomize(image,args[1]);
                break;
               default:
                    System.out.println("Please try again" );
                    break;
        }


    }

}
